/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightsoff_brest_version_console;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author eloisebrest
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    
    private GrilleDeCellules grille;
    private int nbCoups;
    private int nbCoupsMax;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName());

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
        
        int nbLignes = 10;
        int nbColonnes = 10;

        grille = new GrilleDeCellules(nbLignes, nbColonnes);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique bouton_cellule =
                        new CelluleGraphique(grille.getCellule(i, j), 36, 36);
                PanneauGrille.add(bouton_cellule);
            }
        }

        initialiserPartie();
        repaint();
    }

    public void initialiserPartie() {
        nbCoups = 0;
        nbCoupsMax = 20; 
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
        
        texteEtatDeLaPartie.setText("Coups : 0 / " + nbCoupsMax);
        activerTousLesBoutons();
        btnRecommencer.setVisible(false);
    }
    
    private void jouerCoup(Runnable action) {
        action.run();
        nbCoups++;

        texteEtatDeLaPartie.setText("Coups : " + nbCoups + " / " + nbCoupsMax);
        repaint();

        if (grille.cellulesToutesEteintes()) {
            texteEtatDeLaPartie.setText("Victoire en " + nbCoups + " coups !");
            finDePartie();
        } else if (nbCoups >= nbCoupsMax) {
            texteEtatDeLaPartie.setText("Défaite : coups max atteints");
            finDePartie();
        }
    }
    
    
    private void desactiverTousLesBoutons() {
        JButton[] boutons = {
            btnLigne1, btnLigne2, btnLigne3, btnLigne4, btnLigne5,
            btnLigne6, btnLigne7, btnLigne8, btnLigne9, btnLigne10,
            btnColonne1, btnColonne2, btnColonne3, btnColonne4, btnColonne5,
            btnColonne6, btnColonne7, btnColonne8, btnColonne9, btnColonne10,
            btnDiagDesc, btnDiagMont
        };
        for (JButton b : boutons) {
            b.setEnabled(false);
        }
    }
    
    private void activerTousLesBoutons() {
        JButton[] boutons = {
            btnLigne1, btnLigne2, btnLigne3, btnLigne4, btnLigne5,
            btnLigne6, btnLigne7, btnLigne8, btnLigne9, btnLigne10,
            btnColonne1, btnColonne2, btnColonne3, btnColonne4, btnColonne5,
            btnColonne6, btnColonne7, btnColonne8, btnColonne9, btnColonne10,
            btnDiagDesc, btnDiagMont
        };
        for (JButton b : boutons) {
            b.setEnabled(true);
        }
    }
    
    private void finDePartie() {
        desactiverTousLesBoutons();
        btnRecommencer.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        btnLigne1 = new javax.swing.JButton();
        btnLigne2 = new javax.swing.JButton();
        btnLigne3 = new javax.swing.JButton();
        btnLigne4 = new javax.swing.JButton();
        btnLigne5 = new javax.swing.JButton();
        btnLigne6 = new javax.swing.JButton();
        btnLigne7 = new javax.swing.JButton();
        btnLigne8 = new javax.swing.JButton();
        btnLigne9 = new javax.swing.JButton();
        btnLigne10 = new javax.swing.JButton();
        btnColonne1 = new javax.swing.JButton();
        btnColonne2 = new javax.swing.JButton();
        btnColonne3 = new javax.swing.JButton();
        btnColonne4 = new javax.swing.JButton();
        btnColonne5 = new javax.swing.JButton();
        btnColonne6 = new javax.swing.JButton();
        btnColonne7 = new javax.swing.JButton();
        btnColonne8 = new javax.swing.JButton();
        btnColonne9 = new javax.swing.JButton();
        btnColonne10 = new javax.swing.JButton();
        btnDiagDesc = new javax.swing.JButton();
        btnDiagMont = new javax.swing.JButton();
        texteEtatDeLaPartie = new javax.swing.JLabel();
        btnRecommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 400, 400));

        btnLigne1.setText("1L");
        btnLigne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, -1));

        btnLigne2.setText("2L");
        btnLigne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        btnLigne3.setText("3L");
        btnLigne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        btnLigne4.setText("4L");
        btnLigne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, -1));

        btnLigne5.setText("5L");
        btnLigne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, -1));

        btnLigne6.setText("6L");
        btnLigne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 50, -1));

        btnLigne7.setText("7L");
        btnLigne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 50, -1));

        btnLigne8.setText("8L");
        btnLigne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 50, -1));

        btnLigne9.setText("9L");
        btnLigne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 50, -1));

        btnLigne10.setText("10L");
        btnLigne10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 60, -1));

        btnColonne1.setText("1C");
        btnColonne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 50, -1));

        btnColonne2.setText("2C");
        btnColonne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 50, -1));

        btnColonne3.setText("3C");
        btnColonne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 50, -1));

        btnColonne4.setText("4C");
        btnColonne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 50, -1));

        btnColonne5.setText("5C");
        btnColonne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, -1));

        btnColonne6.setText("6C");
        btnColonne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 50, -1));

        btnColonne7.setText("7C");
        btnColonne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 50, -1));

        btnColonne8.setText("8C");
        btnColonne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 50, -1));

        btnColonne9.setText("9C");
        btnColonne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 50, -1));

        btnColonne10.setText("10C");
        btnColonne10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne10, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 470, 60, -1));

        btnDiagDesc.setText("Diagonale descente");
        btnDiagDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagDescActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        btnDiagMont.setText("Diagonale montante");
        btnDiagMont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagMontActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagMont, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        texteEtatDeLaPartie.setText("jLabel1");
        getContentPane().add(texteEtatDeLaPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        btnRecommencer.setText("Recommencer");
        btnRecommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecommencerActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLigne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne1ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(0));
    }//GEN-LAST:event_btnLigne1ActionPerformed

    private void btnLigne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne2ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(1));
    }//GEN-LAST:event_btnLigne2ActionPerformed

    private void btnLigne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne3ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(2));
    }//GEN-LAST:event_btnLigne3ActionPerformed

    private void btnLigne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne4ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(3));
    }//GEN-LAST:event_btnLigne4ActionPerformed

    private void btnLigne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne7ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(6));
    }//GEN-LAST:event_btnLigne7ActionPerformed

    private void btnLigne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne5ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(4));
    }//GEN-LAST:event_btnLigne5ActionPerformed

    private void btnLigne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne6ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(5));
    }//GEN-LAST:event_btnLigne6ActionPerformed

    private void btnLigne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne8ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(7));
    }//GEN-LAST:event_btnLigne8ActionPerformed

    private void btnLigne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne9ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(8));
    }//GEN-LAST:event_btnLigne9ActionPerformed

    private void btnLigne10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne10ActionPerformed
        jouerCoup(() -> grille.activerLigneDeCellules(9));
    }//GEN-LAST:event_btnLigne10ActionPerformed

    private void btnColonne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne1ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(0));
    }//GEN-LAST:event_btnColonne1ActionPerformed

    private void btnColonne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne2ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(1));
    }//GEN-LAST:event_btnColonne2ActionPerformed

    private void btnColonne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne3ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(2));
    }//GEN-LAST:event_btnColonne3ActionPerformed

    private void btnColonne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne4ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(3));
    }//GEN-LAST:event_btnColonne4ActionPerformed

    private void btnColonne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne5ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(4));
    }//GEN-LAST:event_btnColonne5ActionPerformed

    private void btnColonne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne6ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(5));
    }//GEN-LAST:event_btnColonne6ActionPerformed

    private void btnColonne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne7ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(6));
    }//GEN-LAST:event_btnColonne7ActionPerformed

    private void btnColonne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne8ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(7));
    }//GEN-LAST:event_btnColonne8ActionPerformed

    private void btnColonne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne9ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(8));
    }//GEN-LAST:event_btnColonne9ActionPerformed

    private void btnColonne10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne10ActionPerformed
        jouerCoup(() -> grille.activerColonneDeCellules(9));
    }//GEN-LAST:event_btnColonne10ActionPerformed

    private void btnDiagDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagDescActionPerformed
        jouerCoup(() -> grille.activerDiagonaleDescendante());
    }//GEN-LAST:event_btnDiagDescActionPerformed

    private void btnDiagMontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagMontActionPerformed
        jouerCoup(() -> grille.activerDiagonaleMontante());
    }//GEN-LAST:event_btnDiagMontActionPerformed

    private void btnRecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecommencerActionPerformed
        initialiserPartie();
        repaint();
    }//GEN-LAST:event_btnRecommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetrePrincipale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton btnColonne1;
    private javax.swing.JButton btnColonne10;
    private javax.swing.JButton btnColonne2;
    private javax.swing.JButton btnColonne3;
    private javax.swing.JButton btnColonne4;
    private javax.swing.JButton btnColonne5;
    private javax.swing.JButton btnColonne6;
    private javax.swing.JButton btnColonne7;
    private javax.swing.JButton btnColonne8;
    private javax.swing.JButton btnColonne9;
    private javax.swing.JButton btnDiagDesc;
    private javax.swing.JButton btnDiagMont;
    private javax.swing.JButton btnLigne1;
    private javax.swing.JButton btnLigne10;
    private javax.swing.JButton btnLigne2;
    private javax.swing.JButton btnLigne3;
    private javax.swing.JButton btnLigne4;
    private javax.swing.JButton btnLigne5;
    private javax.swing.JButton btnLigne6;
    private javax.swing.JButton btnLigne7;
    private javax.swing.JButton btnLigne8;
    private javax.swing.JButton btnLigne9;
    private javax.swing.JButton btnRecommencer;
    private javax.swing.JLabel texteEtatDeLaPartie;
    // End of variables declaration//GEN-END:variables
}
